# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Interrogation
email: office@critique-gaming.com
description: "Be the lead detective that brings down a mysterious terrorist organisation: The Liberation Front. Use a complex conversational simulation system to interrogate and psychologically manipulate realistic suspects in a noir game about political radicalisation and authority abuse."

og_image: /images/og_image_interrogation.jpg
og_image_width: 1200
og_image_height: 1200
og_type: website
google_analytics_ua: UA-120238989-4

url: "https://interrogation-game.com" # the base hostname & protocol for your site

excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
plugins:
  - kramdown
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 2 versions
  - "ie >= 9"
  - "> 1%"

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'bin']
